name: 'Build Executable'
description: 'Combine frontend and backed of track app into one executable'
inputs:
  pat: #id of input
    description: 'Personal Access Token'
    required: true
    default: ''
  outputs:
    distPath:
      description: 'The path of dist directory'
runs:
  using: 'node12'
  main: 'dist/index.js'
